### ISSUE TITLE
PR Checks workflow fails

### ISSUE THREAD

**Issue by MenaWANG** [alfredodeza/huggingface-ghcr#2]
Hi Alfredo, I was brought here by the Coursera course on MLOps that you taught (THX; I learned heaps from you!!!). One issue I had with the repo is that the PR Checks fail when automatically triggered by a Pull Request. I noticed the same happened in this repo, too: `https://github.com/alfredodeza/huggingface-ghcr/actions/workflows/pr-checks.yml`. 

Do you have any idea why? I am relatively new to GitHub Actions and found it fascinating (thx!). Keen to troubleshoot this one and learn more from it. 

Thx again and your sharing is greatly appreciated!

**Comment by alfredodeza** [comment]
Hey @MenaWANG ! Yes, it is meant to fail on purpose :) You will need to check the logs or log output of the workflow in the Actions tab.
